const pScore=document.getElementById("pkayscore")
const pScore=document.getElementById("pkayscore")
const pScore=document.getElementById("pkayscore")
const pScore=document.getElementById("pkayscore")
const pScore=document.getElementById("pkayscore")